query GetShopFeed(
  $latitude: Float!
  $longitude: Float!
  $take: Int
  $skip: Int
  $cursor: ShopWhereUniqueInput
) {
  shopGetNearbyLocations(
    latitude: $latitude
    longitude: $longitude
    take: $take
    skip: $skip
    cursor: $cursor
  ) {
    createdAt
    id
    name
    _count {
      products
    }
  }
}
